AWSTemplateFormatVersion: '2010-09-09'
Description: iBox - iPlanner Swagger API
Resources:
  AddEventFunction:
    Properties:
      CodeUri: .
      Environment:
        Variables:
          TABLE_NAME:
            Ref: EventTable
      Events:
        AddEventApi:
          Properties:
            Method: PUT
            Path: /events
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: add_event_function.lambda_handler
      MemorySize: 512
      Policies:
      - DynamoDBCrudPolicy:
          TableName:
            Ref: EventTable
      Runtime: python3.6
      Timeout: 50
    Type: AWS::Serverless::Function
  ApiGatewayApi:
    Properties:
      DefinitionBody:
        components:
          schemas:
            Error:
              properties:
                code:
                  format: int32
                  type: integer
                message:
                  type: string
              required:
              - code
              - message
            Event:
              properties:
                activity:
                  type: string
                created:
                  example: 1995-09-07 10:40:52
                  format: date-time
                  type: string
                creator:
                  $ref: '#/components/schemas/User'
                description:
                  type: string
                end:
                  example: 1995-09-07 10:40:52
                  format: date-time
                  type: string
                endTimeUnspecified:
                  type: boolean
                id:
                  format: int64
                  type: integer
                location:
                  type: string
                recurrence:
                  items:
                    type: string
                  type: array
                start:
                  example: 1995-09-07 10:40:52
                  format: date-time
                  type: string
                status:
                  type: string
                summary:
                  type: string
                updated:
                  example: 1995-09-07 10:40:52
                  format: date-time
                  type: string
              required:
              - id
              - summary
              - creator
              - start
              - activity
            Events:
              items:
                $ref: '#/components/schemas/Event'
              type: array
            User:
              properties:
                displayName:
                  type: string
                email:
                  type: string
                id:
                  type: string
                self:
                  type: boolean
              required:
              - id
              - email
              - displayName
              - self
        info:
          title: iPlanner API
          version: 1.0.0
        openapi: 3.0.0
        paths:
          /events:
            post:
              operationId: createEvents
              responses:
                '201':
                  description: Null response
                default:
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
                  description: unexpected error
              summary: Create an event
              tags:
              - events
              x-amazon-apigateway-integration:
                httpMethod: POST
                responses: {}
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AddEventFunction.Arn}/invocations
          /events/{id}:
            get:
              operationId: getEventById
              parameters:
              - description: The id of the event to retrieve
                in: path
                name: id
                required: true
                schema:
                  type: string
              responses:
                '200':
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Event'
                  description: Expected response to a valid request
                default:
                  content:
                    application/json:
                      schema:
                        $ref: '#/components/schemas/Error'
                  description: unexpected error
              summary: Info for a specific event
              tags:
              - events
              x-amazon-apigateway-integration:
                httpMethod: POST
                responses: {}
                type: aws_proxy
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetEventFunction.Arn}/invocations
        x-amazon-apigateway-request-validators:
          Validate query string parameters and headers:
            validateRequestBody: false
            validateRequestParameters: true
      EndpointConfiguration: REGIONAL
      StageName: test
    Type: AWS::Serverless::Api
  EventTable:
    Properties:
      AttributeDefinitions:
      - AttributeName: Activity
        AttributeType: S
      - AttributeName: Creator
        AttributeType: S
      - AttributeName: Start
        AttributeType: S
      KeySchema:
      - AttributeName: Creator
        KeyType: HASH
      - AttributeName: Start
        KeyType: RANGE
      LocalSecondaryIndexes:
      - IndexName: EventKindLocalSecondaryIndex
        KeySchema:
        - AttributeName: Creator
          KeyType: HASH
        - AttributeName: Activity
          KeyType: RANGE
        Projection:
          NonKeyAttributes:
          - Start
          ProjectionType: INCLUDE
      ProvisionedThroughput:
        ReadCapacityUnits: '5'
        WriteCapacityUnits: '5'
      TableName: iplanner_events
    Type: AWS::DynamoDB::Table
  GetEventFunction:
    Properties:
      CodeUri: s3://ibox-sam-bucket/44fe7916f17db5b3ae7f410b81e4e5ca
      Environment:
        Variables:
          TABLE_NAME:
            Ref: EventTable
      Events:
        GetEventByPathApi:
          Properties:
            Method: GET
            Path: /events/{id}
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
        GetEventByQueryApi:
          Properties:
            Method: GET
            Path: /events
            RestApiId:
              Ref: ApiGatewayApi
          Type: Api
      Handler: iplanner_event_functions.get_event_handler
      MemorySize: 512
      Policies:
      - DynamoDBReadPolicy:
          TableName:
            Ref: EventTable
      Runtime: python3.7
      Timeout: 50
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
